# this should be very similar to https://github.com/conda-forge/panblack-feedstock/blob/master/recipe/meta.yaml
# run the following command to create a conda environment that is suitable for testing panblack
# conda env create -f environment.yml
# conda activate panblack
# python -m ipykernel install --user --name panblack --display-name panblack
# and then run this to install panblack in editable mode
# make editable
# update using
# conda env update --name panblack --file environment.yml --prune
name: panblack
channels:
  - conda-forge
dependencies:
  # host:
  - pip
  - python >=3.8
  - poetry >=1,<2
  # run:
  - panflute >=2.1.3,<3
  - defopt >=6,<7
  - psutil >=5,<6
  - tomlkit >=0.7,<0.8
  - "custom-inherit >=2.4,<3"
  # run_constrained:
  - coloredlogs >=14,<16
  - jupytext >=1,<2
  - pandoc >=2.15,<2.17
  # tests:
  - coverage
  - coveralls
  # - flake8
  - pytest
  # - pytest-cov
  # - pytest-parallel
  # - pytest-xdist
  # docs:
  - sphinx
  - sphinx_bootstrap_theme
  - sphinxcontrib-apidoc
  - nbsphinx >=0.8
  - ipykernel
  - pandas
  # dev:
  - pantable >=0.14,<0.15
  - isort
  - mypy
  - bandit
  - black
  - bump2version
  - ghp-import >=2,<3
  - nbconvert >=6,<7
  - pylint
  - rstcheck
  - types-pyyaml
