name: Python package

on: [push, pull_request]

jobs:
  build-n-publish:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # see setup.py for supported versions
        # here instead of having a matrix
        # we only test combinations in a round-robin fashion
        # make sure the versions are monotmonic increasing w.r.t. each other
        # other wise e.g. an older version of a dependency may not work well with a newer version of Python
        include:
          - python-version: "3.8"
            pandoc-version: "2.16"
          - python-version: "3.9"
            pandoc-version: "2.16.1"
          - python-version: "3.10"
            pandoc-version: "latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies—pip
      run: |
        pip install -U pip
        pip install -e .[extras,tests]
    - name: Install dependencies—pandoc
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        [[ ${{ matrix.pandoc-version }} == "latest" ]] && tag= || tag=${{ matrix.pandoc-version }}
        gh release download $tag -R jgm/pandoc -p '*-amd64.deb'
        sudo dpkg -i pandoc-*-amd64.deb
    - name: Sanity check
      run: |
        pip check
        python -c 'import panblack'
    - name: Tests
      run: |
        make test
